#!/usr/bin/perl

use File::Find::Rule;

my $ver = $ARGV[0] ? "./$ARGV[0]" : "." ;

print  "\n";

my $find  = File::Find::Rule;
my @files = $find->file()->name('*.pm','*.t')->in($ver);

foreach my $file (sort @files) {

    #print "criticizing $file\n";
    #die if system "perlcritic --profile=perlcriticrc $file";

    print "tidying $file\n";
    die if system "perltidy --profile=perltidyrc $file";

    if (-f "$file.bak") {
        print "unlinking $file.bak\n";
        unlink "$file.bak";
    }

}
