#!/usr/bin/env perl

BEGIN {

    use FindBin;
    use lib $FindBin::Bin . "/../lib";

}

package MyApp::Basic;

use Validation::Class;

field name => {

    required => 1,

};

field email => {

    required => 1,

};

field type => {

    required => 1,
    options  => [ 'A' .. 'Z' ]

};

field login => {

    # ...

};

field password => {

    required => 1,

};

package main;

my $basic = MyApp::Basic->new(@ARGV);

print $basic->validate(qw/name type/)
    ? "parameters are valid\n"
    : "parameters are invalid\n" . $basic->errors_to_string . "\n";

1;
