#!/usr/bin/env perl

BEGIN {

    use FindBin;
    use lib $FindBin::Bin . "/../lib";

}

# handling arbitrary and/or dynamically-named parameters

package DynamicParameters;

use Validation::Class;

field email     => {
    required    => 1,
    pattern     => qr/\@localhost$/
};

field login     => {
    required    => 1,
    min_length  => 5,
    alias       => ['user']
};

field password  => {
    required    => 1,
    min_length  => 5,
    min_digits  => 1,
    alias       => ['pass']
};

package main;

my $params = {
    user    => 'admin',             # arbitrary
    pass    => 's3cret',            # arbitrary
    email_1 => 'admin@localhost',   # dynamic created
    email_2 => 'root@localhost',    # dynamic created
    email_3 => 'sa@localhost',      # dynamic created
};

my $dp = DynamicParameters->new(params => $params);

$dp->proto->clone_field('email', $_)
    for $dp->params->grep(qr/^email/)->keys
;

print $dp->validate ? "OK" : "NOT OK";
print "\n";

1;
