#!/usr/bin/env perl

BEGIN {

    use FindBin;
    use lib $FindBin::Bin . "/../lib";

}

use Validation::Class::Simple;

my $rules = Validation::Class::Simple->new(
    fields => {
        username    => { required => 1 },
        password    => { required => 1 },
        remember_me => { required => 1, options => ['1|Remember Me?'] }
    }
);

my $fields = $rules->plugin('form_fields');

print "\n"   . $fields->textbox('username');
print "\n"   . $fields->textbox('password', type => 'password');
print "\n"   . $fields->checkgroup('remember_me');
print "\n\n" ;
