#!/usr/bin/perl

BEGIN {

    use FindBin;
    use lib $FindBin::Bin . "/../lib";
    use lib $FindBin::Bin . "/../t/myapp/lib";

}

use strict;
use warnings;

use Data::Dumper;
use Validation::Class::Params;

my $params = Validation::Class::Params->new;

#$params->add(count => {a => {one => 1}, b => {two => 2}, c => {three => [1..9]}});
$params->add(three => [1..9]);


print Dumper $params->flatten->hash;

